# Generated by Django 3.2.8 on 2021-10-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_minuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_makanan', models.IntegerField()),
                ('jumlah_minuman', models.IntegerField()),
                ('makanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makanan.makanan')),
                ('minuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makanan.minuman')),
            ],
        ),
    ]
